### ISSUE TITLE
unable to translate some texts

### ISSUE THREAD

**Issue by Accipiter7** [DavideGalilei/gpytranslate#1]
Example  using asyncio Console
python3 -m asyncio
>>> from gpytranslate import Translator
>>> tr =Translator()
>>> trans= await tr ("shiken")
>>> trans.text
'shiken'

there are many more examples like this where text is not translated

Expected Output:
test
![IMG_2](https://user-images.githubusercontent.com/64995687/93004359-c7bf6c80-f563-11ea-88d6-4efb6a6d4b46.jpg)

**Comment by DavideGalilei** [comment]
Non-Latin languages should be translated using their own characters because the google API endpoint (https://clients5.google.com/translate_a/t) used in this library does not provide a proper json parameter with translation from pronunciation recognition.

To see the [raw API response](https://nekobin.com/mihesemepe), try this snippet:

```
from gpytranslate import Translator
import asyncio

async def main(text: str):
    tr = Translator()
    translation = await tr(text)
    print(translation.raw)
    # If a dict value is "..." access it by his attribute to get the real value
    # Example: translation.raw.sentences

asyncio.run(main("shiken"))
```

I don't know how to fix this to be honest, because it depends on google API.
If you know how to, pull requests are accepted.
